[package]
name        = "scripts"
version     = { workspace = true }
edition     = { workspace = true }
license     = { workspace = true }
authors     = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
